### ISSUE TITLE
Errors compiling kernel module with latest Сentos kernel headers (4.18.0-305.3.1)

### ISSUE THREAD

**Issue by asolovjov** [sipwise/rtpengine#1279]
There are no errors if we compile using kernel-headers-4.18.0-240.22.1.el8_3.x86_64
We get these errors if we install new kernel and kernel-headers-4.18.0-305.3.1.el8.x86_64
```
# make                                                                                                                                                                                                             
make -C /lib/modules/4.18.0-305.3.1.el8.x86_64/build M=/usr/src/rtpengine/kernel-module O=/lib/modules/4.18.0-305.3.1.el8.x86_64/build modules                                                                                              
make[1]: Entering directory '/usr/src/kernels/4.18.0-305.3.1.el8.x86_64'
make[2]: Entering directory '/usr/src/kernels/4.18.0-305.3.1.el8.x86_64'                                                                                                                                                                    
  CC [M]  /usr/src/rtpengine/kernel-module/xt_RTPENGINE.o                                                             
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c: In function ‘send_proxy_packet4’:                                                                                                                                                          
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:3453:42: error: passing argument 2 of ‘ip_route_me_harder’ from incompatible pointer type [-Werror=incompatible-pointer-types]                                                              
  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))                                                                                                                                                                                 
                                          ^~~                                                                                                                                                                                               
In file included from /usr/src/kernels/4.18.0-305.3.1.el8.x86_64/include/uapi/linux/netfilter_ipv4/ip_tables.h:22,                                                                                                                          
                 from /usr/src/kernels/4.18.0-305.3.1.el8.x86_64/include/linux/netfilter_ipv4/ip_tables.h:24,                                                                                                                               
                 from /usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:31:                                                                                                                                                                   
/usr/src/kernels/4.18.0-305.3.1.el8.x86_64/include/linux/netfilter_ipv4.h:19:54: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’                                                                                  
 int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
                                         ~~~~~~~~~~~~~^~                                                                                                                                                                                    
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:3453:6: error: too few arguments to function ‘ip_route_me_harder’                                                                                                                           
  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))                   
      ^~~~~~~~~~~~~~~~~~                                   
In file included from /usr/src/kernels/4.18.0-305.3.1.el8.x86_64/include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from /usr/src/kernels/4.18.0-305.3.1.el8.x86_64/include/linux/netfilter_ipv4/ip_tables.h:24,
                 from /usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:31:
/usr/src/kernels/4.18.0-305.3.1.el8.x86_64/include/linux/netfilter_ipv4.h:19:5: note: declared here
 int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
     ^~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                     
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c: In function ‘send_proxy_packet6’:                                                                                                                                                          
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:3553:43: error: passing argument 2 of ‘ip6_route_me_harder’ from incompatible pointer type [-Werror=incompatible-pointer-types]                                                             
  if (ip6_route_me_harder(par->state->net, skb))                                                                                                                                                                                            
                                           ^~~                                                                                                                                                                                              
In file included from /usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:33:                                                                                                                                                                   
/usr/src/kernels/4.18.0-305.3.1.el8.x86_64/include/linux/netfilter_ipv6.h:89:55: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’                                                                                  
 int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
                                          ~~~~~~~~~~~~~^~                                                                                                                                                                                   
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:3553:6: error: too few arguments to function ‘ip6_route_me_harder’
  if (ip6_route_me_harder(par->state->net, skb))
      ^~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                   
In file included from /usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:33:
/usr/src/kernels/4.18.0-305.3.1.el8.x86_64/include/linux/netfilter_ipv6.h:89:5: note: declared here
 int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);                                                                                                                                                            
     ^~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                    
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/kernels/4.18.0-305.3.1.el8.x86_64/scripts/Makefile.build:322: /usr/src/rtpengine/kernel-module/xt_RTPENGINE.o] Error 1                                                                                               
make[2]: *** [/usr/src/kernels/4.18.0-305.3.1.el8.x86_64/Makefile:1563: _module_/usr/src/rtpengine/kernel-module] Error 2                                                                                                                   
make[2]: Leaving directory '/usr/src/kernels/4.18.0-305.3.1.el8.x86_64'      
make[1]: *** [Makefile:157: sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.18.0-305.3.1.el8.x86_64'                                                                                                                                                                     
make: *** [Makefile:34: modules] Error 2       
```

**Comment by rfuchs** [comment]
What does `uname -a` say for this kernel?

Looks like either a patched or unreleased version of the kernel because I'm not seeing that change in https://elixir.bootlin.com/linux/v4.18.20/source/include/linux/netfilter_ipv4.h

**Comment by rfuchs** [comment]
No idea if this is the Red Hat appropriate way of doing this, but see 417d2cf
