### ISSUE TITLE
Kernel module fails to build on 6.13

### ISSUE THREAD

**Issue by linuxmaniac** [sipwise/rtpengine#1898]
### rtpengine version the issue has been seen with

12.5.1.18

### Used distribution and its version

Debian sid

### Linux kernel version used

6.13-rc6-amd64

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Additional program output to the terminal or logs illustrating the issue

```shell
rtpengine-kernel-dkms fails to build a module for Linux 6.13 in
experimental:

DKMS make.log for rtpengine-12.5.1.18 for kernel 6.13-rc6-amd64 (x86_64)
Tue Jan 14 22:26:51 UTC 2025
make: Entering directory '/usr/src/linux-headers-6.13-rc6-amd64'
make[1]: Entering directory '/var/lib/dkms/rtpengine/12.5.1.18/build'
  CC [M]  xt_RTPENGINE.o
In file included from /usr/src/linux-headers-6.13-rc6-common/include/linux/module.h:22,
                 from xt_RTPENGINE.c:2:
xt_RTPENGINE.c:48:18: error: expected ',' or ';' before 'CRYPTO_INTERNAL'
   48 | MODULE_IMPORT_NS(CRYPTO_INTERNAL);
      |                  ^~~~~~~~~~~~~~~
/usr/src/linux-headers-6.13-rc6-common/include/linux/moduleparam.h:26:61: note: in definition of macro '__MODULE_INFO'
   26 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
      |                                                             ^~~~
/usr/src/linux-headers-6.13-rc6-common/include/linux/module.h:299:33: note: in expansion of macro 'MODULE_INFO'
  299 | #define MODULE_IMPORT_NS(ns)    MODULE_INFO(import_ns, ns)
      |                                 ^~~~~~~~~~~
xt_RTPENGINE.c:48:1: note: in expansion of macro 'MODULE_IMPORT_NS'
   48 | MODULE_IMPORT_NS(CRYPTO_INTERNAL);
      | ^~~~~~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-6.13-rc6-common/scripts/Makefile.build:199: xt_RTPENGINE.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.13-rc6-common/Makefile:2013: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.13-rc6-common/Makefile:263: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/rtpengine/12.5.1.18/build'
make: *** [/usr/src/linux-headers-6.13-rc6-common/Makefile:263: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.13-rc6-amd64'
```

### Anything else?

Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1093095
