### ISSUE TITLE
Build failure with 5.8-aws kernel

### ISSUE THREAD

**Issue by jamusan** [sipwise/rtpengine#1326]
I have a build error with kernel version 5.8.0-1041-aws. And this is related to #1111.
The quick fix could be:
<details>
  <summary>diff</summary>

```
--- xt_RTPENGINE.c      2021-08-04 16:57:04.520811045 +0000
+++ xt_RTPENGINE.c-fix  2021-08-04 16:57:56.637678570 +0000
@@ -3562,7 +3562,7 @@

        skb->protocol = htons(ETH_P_IP);
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(5,9,9) || \
-               (LINUX_VERSION_CODE >= KERNEL_VERSION(5,4,78) && LINUX_VERSION_CODE < KERNEL_VERSION(5,5,0)) || \
+               (LINUX_VERSION_CODE >= KERNEL_VERSION(5,4,78) && LINUX_VERSION_CODE < KERNEL_VERSION(5,9,0)) || \
                (LINUX_VERSION_CODE >= KERNEL_VERSION(4,19,158) && LINUX_VERSION_CODE < KERNEL_VERSION(4,20,0))
        if (ip_route_me_harder(par->state->net, par->state->sk, skb, RTN_UNSPEC))
 #elif defined(RHEL_RELEASE_CODE) && LINUX_VERSION_CODE >= KERNEL_VERSION(4,18,0) && \
@@ -3665,7 +3665,7 @@

        skb->protocol = htons(ETH_P_IPV6);
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(5,9,9) || \
-               (LINUX_VERSION_CODE >= KERNEL_VERSION(5,4,78) && LINUX_VERSION_CODE < KERNEL_VERSION(5,5,0)) || \
+               (LINUX_VERSION_CODE >= KERNEL_VERSION(5,4,78) && LINUX_VERSION_CODE < KERNEL_VERSION(5,9,0)) || \
                (LINUX_VERSION_CODE >= KERNEL_VERSION(4,19,158) && LINUX_VERSION_CODE < KERNEL_VERSION(4,20,0))
        if (ip6_route_me_harder(par->state->net, par->state->sk, skb))
 #elif defined(RHEL_RELEASE_CODE) && LINUX_VERSION_CODE >= KERNEL_VERSION(4,18,0) && \
```
</details>
<details>
  <summary>lsb_release -a</summary>

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
</details>
<details>
  <summary>uname -a</summary>

```
Linux ip 5.8.0-1041-aws #43~20.04.1-Ubuntu SMP Thu Jul 15 11:07:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
</details>
<details>
  <summary>git log --format="%H" -n 1</summary>

```
b0c97e4ccccfa1bcb045730c0b70fdef189df30d
```
</details>
<details>
  <summary>dpkg -i ngcp-rtpengine-kernel-dkms_10.0.0.0+0~mr10.0.0.0_all.deb</summary>

```
(Reading database ... 84313 files and directories currently installed.)
Preparing to unpack ngcp-rtpengine-kernel-dkms_10.0.0.0+0~mr10.0.0.0_all.deb ...

------------------------------
Deleting module version: 10.0.0.0+0~mr10.0.0.0
completely from the DKMS tree.
------------------------------
Done.
Unpacking ngcp-rtpengine-kernel-dkms (10.0.0.0+0~mr10.0.0.0) over (10.0.0.0+0~mr10.0.0.0) ...
Setting up ngcp-rtpengine-kernel-dkms (10.0.0.0+0~mr10.0.0.0) ...

Creating symlink /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/source ->
                 /usr/src/ngcp-rtpengine-10.0.0.0+0~mr10.0.0.0

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j1 KERNELRELEASE=5.8.0-1041-aws -C /lib/modules/5.8.0-1041-aws/build M=/var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build RTPENGINE_VERSION=10.0.0.0+0~mr10.0.0.0...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.8.0-1041-aws (x86_64)
Consult /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/make.log for more information.
```
</details>
<details>
  <summary>/var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/make.log</summary>

```
DKMS make.log for ngcp-rtpengine-10.0.0.0+0~mr10.0.0.0 for kernel 5.8.0-1041-aws (x86_64)
Wed Aug  4 15:37:26 UTC 2021
make: Entering directory '/usr/src/linux-headers-5.8.0-1041-aws'
  AR      /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/built-in.a
  CC [M]  /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.o
/var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c: In function ‘send_proxy_packet4’:
/var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c:3572:42: error: passing argument 2 of ‘ip_route_me_harder’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 3572 |  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))
      |                                          ^~~
      |                                          |
      |                                          struct sk_buff *
In file included from ./include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from ./include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c:31:
./include/linux/netfilter_ipv4.h:19:54: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’
   19 | int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
      |                                         ~~~~~~~~~~~~~^~
/var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c:3572:6: error: too few arguments to function ‘ip_route_me_harder’
 3572 |  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))
      |      ^~~~~~~~~~~~~~~~~~
In file included from ./include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from ./include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c:31:
./include/linux/netfilter_ipv4.h:19:5: note: declared here
   19 | int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
      |     ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c: In function ‘send_proxy_packet6’:
/var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c:3675:43: error: passing argument 2 of ‘ip6_route_me_harder’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 3675 |  if (ip6_route_me_harder(par->state->net, skb))
      |                                           ^~~
      |                                           |
      |                                           struct sk_buff *
In file included from /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c:33:
./include/linux/netfilter_ipv6.h:146:55: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’
  146 | int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
      |                                          ~~~~~~~~~~~~~^~
/var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c:3675:6: error: too few arguments to function ‘ip6_route_me_harder’
 3675 |  if (ip6_route_me_harder(par->state->net, skb))
      |      ^~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.c:33:
./include/linux/netfilter_ipv6.h:146:5: note: declared here
  146 | int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
      |     ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:286: /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build/xt_RTPENGINE.o] Error 1
make: *** [Makefile:1785: /var/lib/dkms/ngcp-rtpengine/10.0.0.0+0~mr10.0.0.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.8.0-1041-aws'
```
</details>

**Comment by rfuchs** [comment]
Unfortunately Ubuntu seems to be using a patched kernel without a way to detect it (that I know of) so I see no way of fixing this without breaking non-Ubuntu builds.

**Comment by thuroc** [comment]
Hello,

we have the same problem with the version 7.5.
Are there any efforts to fix the whole thing in a timely manner?
We use the rtpengine in our entire network with over 100 servers and the error is very critical for us.

**Comment by rfuchs** [comment]
As I explained above, I see no way of fixing this in the mainline code base without breaking it for everybody else. Complain to Ubuntu for using an undetectable patched kernel.
