### ISSUE TITLE
Build error on Ubuntu Focal 20.04 LTS and RTP Engine 9.5.6.7.0~mr9.5.6.7

### ISSUE THREAD

**Issue by mromero-convoso** [sipwise/rtpengine#1733]
Using revision `f35d19cf0a7d6a3a5c180244434941f9f97c6993` on Ubuntu Focal 20.04 LTS, where this specific revision tag was previously building correctly, I am now facing an issue with the `ngcp-rtpengine-kernel-dkms_9.5.6.7+0~mr9.5.6.7_all.deb` package failing to build the `xt_RTPENGINE.o` module, and subsequently failing to copy to /var/lib/modules/`uname -r`

The output from a `dpkg -i ngcp-rtpengine-kernel-dkms_9.5.6.7+0~mr9.5.6.7_all.deb`: 
```
root@default-ubuntu-2004:/usr/local/src# dpkg -i ngcp-rtpengine-kernel-dkms_9.5.6.7+0~mr9.5.6.7_all.deb
(Reading database ... 99183 files and directories currently installed.)
Preparing to unpack ngcp-rtpengine-kernel-dkms_9.5.6.7+0~mr9.5.6.7_all.deb ...

------------------------------
Deleting module version: 9.5.6.7+0~mr9.5.6.7
completely from the DKMS tree.
------------------------------
Done.
Unpacking ngcp-rtpengine-kernel-dkms (9.5.6.7+0~mr9.5.6.7) over (9.5.6.7+0~mr9.5.6.7) ...
Setting up ngcp-rtpengine-kernel-dkms (9.5.6.7+0~mr9.5.6.7) ...

Creating symlink /var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/source ->
                 /usr/src/ngcp-rtpengine-9.5.6.7+0~mr9.5.6.7

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j1 KERNELRELEASE=5.4.0-58-generic -C /lib/modules/5.4.0-58-generic/build M=/var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build RTPENGINE_VERSION=9.5.6.7+0~mr9.5.6.7...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.0-58-generic (x86_64)
Consult /var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/make.log for more information.
root@default-ubuntu-2004:/usr/local/src#
```

The contents of the `make.log` mentioned in the output above:
```
root@default-ubuntu-2004:/usr/local/src# cat /var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/make.log
DKMS make.log for ngcp-rtpengine-9.5.6.7+0~mr9.5.6.7 for kernel 5.4.0-58-generic (x86_64)
Thu 05 Oct 2023 06:07:25 PM UTC
make: Entering directory '/usr/src/linux-headers-5.4.0-58-generic'
  AR      /var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/built-in.a
  CC [M]  /var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/xt_RTPENGINE.o
/var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/xt_RTPENGINE.c: In function ‘send_proxy_packet4’:
/var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/xt_RTPENGINE.c:3460:44: error: missing binary operator before token "("
 3460 |   RHEL_RELEASE_CODE >= RHEL_RELEASE_VERSION(8,4)
      |                                            ^
/var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/xt_RTPENGINE.c: In function ‘send_proxy_packet6’:
/var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/xt_RTPENGINE.c:3563:44: error: missing binary operator before token "("
 3563 |   RHEL_RELEASE_CODE >= RHEL_RELEASE_VERSION(8,4)
      |                                            ^
make[1]: *** [scripts/Makefile.build:275: /var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build/xt_RTPENGINE.o] Error 1
make: *** [Makefile:1757: /var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.4.0-58-generic'
root@default-ubuntu-2004:/usr/local/src#
```

The `ngcp-rtpengine-daemon` service starts, but is missing xt_RTPENGINE, as seen from this `systemctl status ngcp-rtpengine-daemon` output:
```
root@default-ubuntu-2004:/usr/local/src# systemctl status ngcp-rtpengine-daemon
● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
     Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-10-05 18:07:28 UTC; 3min 58s ago
    Process: 67619 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=0/SUCCESS)
   Main PID: 67648 (rtpengine)
      Tasks: 22 (limit: 1074)
     Memory: 7.1M
     CGroup: /system.slice/ngcp-rtpengine-daemon.service
             └─67648 /usr/sbin/rtpengine -f -E --config-file /etc/rtpengine/rtpengine.conf

Oct 05 18:07:28 default-ubuntu-2004 systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Oct 05 18:07:28 default-ubuntu-2004 ngcp-rtpengine-iptables-setup[67621]: modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/5.4.0-58-generic
Oct 05 18:07:28 default-ubuntu-2004 ngcp-rtpengine-iptables-setup[67638]: iptables v1.8.4 (legacy): unknown option "--id"
Oct 05 18:07:28 default-ubuntu-2004 ngcp-rtpengine-iptables-setup[67638]: Try `iptables -h' or 'iptables --help' for more information.
Oct 05 18:07:28 default-ubuntu-2004 ngcp-rtpengine-iptables-setup[67646]: ip6tables v1.8.4 (legacy): unknown option "--id"
Oct 05 18:07:28 default-ubuntu-2004 ngcp-rtpengine-iptables-setup[67646]: Try `ip6tables -h' or 'ip6tables --help' for more information.
Oct 05 18:07:28 default-ubuntu-2004 rtpengine[67648]: [1696529248.620908] INFO: [crypto] Generating new DTLS certificate
Oct 05 18:07:28 default-ubuntu-2004 rtpengine[67648]: [1696529248.662447] ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
Oct 05 18:07:28 default-ubuntu-2004 rtpengine[67648]: [1696529248.665443] INFO: [core] Startup complete, version 9.5.6.7+0~mr9.5.6.7 git-HEAD-f35d19cf
Oct 05 18:07:28 default-ubuntu-2004 systemd[1]: Started NGCP RTP/media Proxy Daemon.
root@default-ubuntu-2004:/usr/local/src#
```

**Comment by mromero-convoso** [comment]
@rfuchs applying the patch mentioned above was successful. After re-running `dpkg-buildpackage` with the patch applied, and re-installing `ngcp-rtpengine-kernel-dkms_9.5.6.7+0~mr9.5.6.7_all.deb` we see:
```
root@default-ubuntu-2004:/usr/local/src# dpkg -i ngcp-rtpengine-kernel-dkms_9.5.6.7+0~mr9.5.6.7_all.deb
(Reading database ... 106873 files and directories currently installed.)
Preparing to unpack ngcp-rtpengine-kernel-dkms_9.5.6.7+0~mr9.5.6.7_all.deb ...

------------------------------
Deleting module version: 9.5.6.7+0~mr9.5.6.7
completely from the DKMS tree.
------------------------------
Done.
Unpacking ngcp-rtpengine-kernel-dkms (9.5.6.7+0~mr9.5.6.7) over (9.5.6.7+0~mr9.5.6.7) ...
Setting up ngcp-rtpengine-kernel-dkms (9.5.6.7+0~mr9.5.6.7) ...

Creating symlink /var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/source ->
                 /usr/src/ngcp-rtpengine-9.5.6.7+0~mr9.5.6.7

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j1 KERNELRELEASE=5.4.0-58-generic -C /lib/modules/5.4.0-58-generic/build M=/var/lib/dkms/ngcp-rtpengine/9.5.6.7+0~mr9.5.6.7/build RTPENGINE_VERSION=9.5.6.7+0~mr9.5.6.7....
cleaning build area...

DKMS: build completed.

xt_RTPENGINE.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.0-58-generic/updates/dkms/

depmod....

DKMS: install completed.
root@default-ubuntu-2004:/usr/local/src#
```
Restarting the `ngcp-rtpengine-daemon` service and running a `systemctl status ngcp-rtpengine-daemon` we now see the process start without error:
```
root@default-ubuntu-2004:/usr/local/src# systemctl status ngcp-rtpengine-daemon
● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
     Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-10-05 18:45:14 UTC; 4s ago
    Process: 172818 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=0/SUCCESS)
   Main PID: 172843 (rtpengine)
      Tasks: 22 (limit: 1074)
     Memory: 7.1M
     CGroup: /system.slice/ngcp-rtpengine-daemon.service
             └─172843 /usr/sbin/rtpengine -f -E --config-file /etc/rtpengine/rtpengine.conf

Oct 05 18:45:14 default-ubuntu-2004 systemd[1]: Stopped NGCP RTP/media Proxy Daemon.
Oct 05 18:45:14 default-ubuntu-2004 systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Oct 05 18:45:14 default-ubuntu-2004 rtpengine[172843]: [1696531514.808567] INFO: [crypto] Generating new DTLS certificate
Oct 05 18:45:14 default-ubuntu-2004 rtpengine[172843]: [1696531514.842811] INFO: [core] Startup complete, version 9.5.6.7+0~mr9.5.6.7 git-HEAD-f35d19cf
Oct 05 18:45:14 default-ubuntu-2004 systemd[1]: Started NGCP RTP/media Proxy Daemon.
root@default-ubuntu-2004:/usr/local/src#
```

My only question is how this bug crept into the build when we had specifically tagged the version of the RTP engine source via revision id @ revision `f35d19cf0a7d6a3a5c180244434941f9f97c6993` - any idea there? We like to lock down our environment as much as possible so builds are repeatable and this one was a bit of a shocker.

**Comment by rfuchs** [comment]
> My only question is how this bug crept into the build when we had specifically tagged the version of the RTP engine source via revision id @ revision `f35d19cf0a7d6a3a5c180244434941f9f97c6993` - any idea there? We like to lock down our environment as much as possible so builds are repeatable and this one was a bit of a shocker.

I can only guess that perhaps your host's kernel got updated to a new version which activated use of these macros, while with an older version the macros were left unevaluated.
