### ISSUE TITLE
Kernel module (master branch) fails to build with kernel-5.2.8 (Fedora x86_64)

### ISSUE THREAD

**Issue by amessina** [sipwise/rtpengine#826]
```
/usr/bin/make -C /usr/src/kernels/5.2.8-200.fc30.x86_64 M=/builddir/build/BUILD/rtpengine-kmod-7.2.2.1/_kmod_build_5.2.8-200.fc30.x86_64 O=/usr/src/kernels/5.2.8-200.fc30.x86_64 modules
  CC [M]  /builddir/build/BUILD/rtpengine-kmod-7.2.2.1/_kmod_build_5.2.8-200.fc30.x86_64/xt_RTPENGINE.o
BUILDSTDERR: /builddir/build/BUILD/rtpengine-kmod-7.2.2.1/_kmod_build_5.2.8-200.fc30.x86_64/xt_RTPENGINE.c: In function 'srtp_hash':
BUILDSTDERR: /builddir/build/BUILD/rtpengine-kmod-7.2.2.1/_kmod_build_5.2.8-200.fc30.x86_64/xt_RTPENGINE.c:3569:5: error: 'struct shash_desc' has no member named 'flags'
BUILDSTDERR:  3569 |  dsc->flags = 0;
BUILDSTDERR:       |     ^~
BUILDSTDERR: make[2]: *** [scripts/Makefile.build:285: /builddir/build/BUILD/rtpengine-kmod-7.2.2.1/_kmod_build_5.2.8-200.fc30.x86_64/xt_RTPENGINE.o] Error 1
BUILDSTDERR: make[1]: *** [Makefile:1601: _module_/builddir/build/BUILD/rtpengine-kmod-7.2.2.1/_kmod_build_5.2.8-200.fc30.x86_64] Error 2
BUILDSTDERR: make: *** [Makefile:34: modules] Error 2
```

**Comment by amessina** [comment]
Thank you @rfuchs for the very quick turnaround.
