### ISSUE TITLE
Trying to install rtpengine on Debian AWS EC2 instance, dkms failing

### ISSUE THREAD

**Issue by churnd** [sipwise/rtpengine#1378]
Seems to be related to the kind of kernel the Debian EC2 instance uses:

```
# apt install --reinstall ngcp-rtpengine-daemon ngcp-rtpengine-iptables ngcp-rtpengine-kernel-dkms ngcp-rtpengine-utils
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  keyutils libnfsidmap2 libtirpc-common libtirpc3
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 4 reinstalled, 0 to remove and 2 not upgraded.
Need to get 0 B/409 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 59126 files and directories currently installed.)
Preparing to unpack .../ngcp-rtpengine-daemon_8.0.1.1+0~mr8.0.1.1_amd64.deb ...
Unpacking ngcp-rtpengine-daemon (8.0.1.1+0~mr8.0.1.1) over (8.0.1.1+0~mr8.0.1.1) ...
Preparing to unpack .../ngcp-rtpengine-iptables_8.0.1.1+0~mr8.0.1.1_amd64.deb ...
Unpacking ngcp-rtpengine-iptables (8.0.1.1+0~mr8.0.1.1) over (8.0.1.1+0~mr8.0.1.1) ...
Preparing to unpack .../ngcp-rtpengine-kernel-dkms_8.0.1.1+0~mr8.0.1.1_all.deb ...

------------------------------
Deleting module version: 8.0.1.1+0~mr8.0.1.1
completely from the DKMS tree.
------------------------------
Done.
Unpacking ngcp-rtpengine-kernel-dkms (8.0.1.1+0~mr8.0.1.1) over (8.0.1.1+0~mr8.0.1.1) ...
Preparing to unpack .../ngcp-rtpengine-utils_8.0.1.1+0~mr8.0.1.1_all.deb ...
Unpacking ngcp-rtpengine-utils (8.0.1.1+0~mr8.0.1.1) over (8.0.1.1+0~mr8.0.1.1) ...
Setting up ngcp-rtpengine-kernel-dkms (8.0.1.1+0~mr8.0.1.1) ...

Creating symlink /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/source ->
                 /usr/src/ngcp-rtpengine-8.0.1.1+0~mr8.0.1.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j2 KERNELRELEASE=4.19.0-18-cloud-amd64 -C /lib/modules/4.19.0-18-cloud-amd64/build M=/var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build RTPENGINE_VERSION=8.0.1.1+0~mr8.0.1.1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.0-18-cloud-amd64 (x86_64)
Consult /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/make.log for more information.
Setting up ngcp-rtpengine-daemon (8.0.1.1+0~mr8.0.1.1) ...
Setting up ngcp-rtpengine-iptables (8.0.1.1+0~mr8.0.1.1) ...
Setting up ngcp-rtpengine-utils (8.0.1.1+0~mr8.0.1.1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for systemd (241-7~deb10u8) ...
```

```
# cat /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/make.log
DKMS make.log for ngcp-rtpengine-8.0.1.1+0~mr8.0.1.1 for kernel 4.19.0-18-cloud-amd64 (x86_64)
Tue Oct 12 20:36:30 UTC 2021
make: Entering directory '/usr/src/linux-headers-4.19.0-18-cloud-amd64'
  CC [M]  /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.o
/var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c: In function ‘send_proxy_packet4’:
/var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c:3297:42: error: passing argument 2 of ‘ip_route_me_harder’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))
                                          ^~~
In file included from /usr/src/linux-headers-4.19.0-18-common/include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from /usr/src/linux-headers-4.19.0-18-common/include/linux/netfilter_ipv4/ip_tables.h:24,
                 from /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c:24:
/usr/src/linux-headers-4.19.0-18-common/include/linux/netfilter_ipv4.h:19:54: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’
 int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
                                         ~~~~~~~~~~~~~^~
/var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c:3297:6: error: too few arguments to function ‘ip_route_me_harder’
  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))
      ^~~~~~~~~~~~~~~~~~
In file included from /usr/src/linux-headers-4.19.0-18-common/include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from /usr/src/linux-headers-4.19.0-18-common/include/linux/netfilter_ipv4/ip_tables.h:24,
                 from /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c:24:
/usr/src/linux-headers-4.19.0-18-common/include/linux/netfilter_ipv4.h:19:5: note: declared here
 int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
     ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c: In function ‘send_proxy_packet6’:
/var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c:3393:43: error: passing argument 2 of ‘ip6_route_me_harder’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  if (ip6_route_me_harder(par->state->net, skb))
                                           ^~~
In file included from /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c:26:
/usr/src/linux-headers-4.19.0-18-common/include/linux/netfilter_ipv6.h:39:55: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’
 int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
                                          ~~~~~~~~~~~~~^~
/var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c:3393:6: error: too few arguments to function ‘ip6_route_me_harder’
  if (ip6_route_me_harder(par->state->net, skb))
      ^~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.c:26:
/usr/src/linux-headers-4.19.0-18-common/include/linux/netfilter_ipv6.h:39:5: note: declared here
 int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
     ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-4.19.0-18-common/scripts/Makefile.build:315: /var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build/xt_RTPENGINE.o] Error 1
make[2]: *** [/usr/src/linux-headers-4.19.0-18-common/Makefile:1561: _module_/var/lib/dkms/ngcp-rtpengine/8.0.1.1+0~mr8.0.1.1/build] Error 2
make[1]: *** [Makefile:146: sub-make] Error 2
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/usr/src/linux-headers-4.19.0-18-cloud-amd64'
```

```
# uname -a
Linux ip-10-5-101-41 4.19.0-18-cloud-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
