### ISSUE TITLE
Compile issue on Centos 6

### ISSUE THREAD

**Issue by mtryfoss** [sipwise/rtpengine#76]
Make returns this:

call.o: In function `bf_set':
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
call.o: In function `bf_clear':
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:486: undefined reference to `g_atomic_int_and'
call.o: In function `bf_set':
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
call.o: In function `bf_clear':
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:486: undefined reference to `g_atomic_int_and'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:486: undefined reference to `g_atomic_int_and'
call.o: In function `bf_set':
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
call.o: In function `bf_clear':
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:486: undefined reference to `g_atomic_int_and'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:486: undefined reference to `g_atomic_int_and'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:486: undefined reference to `g_atomic_int_and'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:486: undefined reference to `g_atomic_int_and'
call.o: In function `bf_set':
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:483: undefined reference to `g_atomic_int_or'
call.o: In function `atomic64_add':
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:545: undefined reference to `g_atomic_pointer_add'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:545: undefined reference to `g_atomic_pointer_add'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:545: undefined reference to `g_atomic_pointer_add'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:545: undefined reference to `g_atomic_pointer_add'
/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:545: undefined reference to `g_atomic_pointer_add'
call.o:/root/rpmbuild/SOURCES/ngcp-rtpengine-2.3.6/daemon/aux.h:545: more undefined references to `g_atomic_pointer_add' follow

gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

**Comment by rfuchs** [comment]
Which version of glib is this?

**Comment by mtryfoss** [comment]
Hi,

The installed version is glib2-devel.x86_64 2.28.8-4.el6

**Comment by nakchak** [comment]
For what its worth I have no issues compiling on a fully up-to-date centos 6 box, compiling against master.  Although I only run the make scripts not the rpm build.  Followed instructions here and never had an issue building http://caruizdiaz.com/2014/01/03/installing-mediaproxy-ng/

Ignore references to mediaproxy-Ng old name for rtpengine...

**Comment by mtryfoss** [comment]
I'm comparing with an ubuntu-server. 

/usr/include/glib-2.0/glib/gatomic.h does not have for example "g_atomic_int_and" referenced in aux.h on centos like ubuntu.

**Comment by rfuchs** [comment]
These are from glib 2.30 (and up). If @nakchak can compile on CentOS 6, then there's probably an upgrade available?

**Comment by mtryfoss** [comment]
That sounds strange. Everything else on the system is built using the older version. That might cause conflicts.

**Comment by rfuchs** [comment]
It shouldn't, glib has a stable ABI.

**Comment by arsenx** [comment]
I am having the same issue, it seems to be some outdated package issue. I tried installing on Centos 6.5 and get the same issue but installation on Centos 7 works seamlessly.

**Comment by etamme** [comment]
we've also run into this issue.

compiles fine against glib2-devel-2.22.5-6.el6.x86_64 (centos 6.2)
fails against glib2-devel-2.28.8-4.el6.x86_64 (centos 6.6)
compiles fine against glib2-devel-2.36.3-5.el7.x86_64 (centos 7)

**Comment by alexcme** [comment]
@nakchak I think confusion is that you referenced manual for **x86**, i.e.  from the link - "Before you begin: I’m using a x86 virtual machine. This means that you have to change the package names from i686 to x86_64 when necessary". x86_64 build unfortunately still have problems on CentOS 6.5 / 6.6

**Comment by alexcme** [comment]
@nakchak @rfuchs , just installed latest CentOS 6.6 x86 and still have problem(s), but now only two undefines:

ice.o: In function `bf_set':
/home/alexc/repo/rtpengine/daemon/aux.h:643: undefined reference to `g_atomic_int_or'
ice.o: In function `bf_clear':
/home/alexc/repo/rtpengine/daemon/aux.h:647: undefined reference to `g_atomic_int_and'

**Comment by alexcme** [comment]
As mentioned above - it just impossible to integrate any recent changes into CentOS 6.5/6.6 (glib2-devel-2.28.x)

**Comment by alexcme** [comment]
Installed CentOS 6.2 (x86_64), have the same issues as in 6.5 or 6,6:

aux.h: In function ‘bf_set’:
aux.h:643: warning: implicit declaration of function ‘g_atomic_int_or’
aux.h: In function ‘bf_clear’:
aux.h:647: warning: implicit declaration of function ‘g_atomic_int_and’
aux.h: In function ‘atomic64_add’:
aux.h:712: warning: implicit declaration of function ‘g_atomic_pointer_add’
aux.h: In function ‘atomic64_get_set’:
aux.h:721: warning: passing argument 1 of ‘g_atomic_pointer_compare_and_exchange’ from incompatible pointer type

**Comment by etamme** [comment]
you are missing glib

**Comment by alexcme** [comment]
How? what I have is:

[alexc@centos62anc daemon]$ su
Password: 
[root@centos62anc daemon]# yum install glib2-devel
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
 * base: mirror.raystedman.net
 * extras: mirrors.centarra.com
 * updates: centos.arvixe.com
Setting up Install Process
Package glib2-devel-2.28.8-4.el6.x86_64 already installed and latest version
Nothing to do
[root@centos62anc daemon]#

**Comment by alexcme** [comment]
How? what I have is:

[alexc@centos62anc daemon]$ su
Password: 
[root@centos62anc daemon]# yum install glib2-devel
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile

base: mirror.raystedman.net
extras: mirrors.centarra.com
updates: centos.arvixe.com Setting up Install Process Package glib2-devel-2.28.8-4.el6.x86_64 already installed and latest version Nothing to do

root@centos62anc daemon]#

-Alex

**Comment by ibaques** [comment]
Hi @alexcme can you explain how you maked the link to compile in 6.5?

**Comment by rfuchs** [comment]
I've taken the glib2 source package from CentOS 7.0 and rebuilt it under CentOS 6.6 (amd64). The resulting RPMs are here:

http://dfx.at/glib2-2.36.3-5.el6/

There's a warning when you install it (from `gio-querymodules-64`), but AFAICT it still works fine, at least for rtpengine. I can't vouch for any software using the GIO system though, so YMMV.

**Comment by ibaques** [comment]
Hi @rfuchs it works perfectly! thanks

**Comment by etamme** [comment]
adding further info to this issue:

We are able to build the daemon against yum provided glib on centos 6.2 as of commit:

commit 458a84c1d2b2a39f43e6c687b69116cfb2be5e31
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Mon Jan 5 10:03:10 2015 -0500

However we are NOT able to build the daemon against yum provided glib on centos 6.2 on current master:

commit 8ca711e8e222c5ac527129ed5ac0e7ba57ac6cd9
Merge: d17ea83 e14908c
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Tue Aug 4 10:31:25 2015 -0400

    Merge branch 'smititelu-master'

So some thing in the rtpengine project was added or changed to make it not compile against yum provided glib on centos 6.2 between those dates

**Comment by joseph-onsip** [comment]
> So some thing in the rtpengine project was added or changed to make it not compile against yum provided glib on centos 6.2 between those dates

I've discussed this with @etamme, but for everyone else's benefit: In case it wasn't clear, this appears to be the relevant commit: https://github.com/sipwise/rtpengine/commit/26ca844

**Comment by paulandrewhughes** [comment]
In glib 2.30 the missing functions are defined in macros when gcc is the compiler:
Adding these definitions as follows after the #include statements in aux.h allows code to compile on centos6.7 and other platforms that lack glib 2.30 but have the required gcc extensions.
```
#if !(GLIB_CHECK_VERSION(2,30,0))
#define g_atomic_int_and(atomic, val) \
(G_GNUC_EXTENSION ({                                                          \
G_STATIC_ASSERT (sizeof *(atomic) == sizeof (gint));                     \
(void) (0 ? *(atomic) ^ (val) : 0);                                      \
(guint) __sync_fetch_and_and ((atomic), (val));                          \
}))
#define g_atomic_int_or(atomic, val) \
(G_GNUC_EXTENSION ({                                                          \
G_STATIC_ASSERT (sizeof *(atomic) == sizeof (gint));                     \
(void) (0 ? *(atomic) ^ (val) : 0);                                      \
(guint) __sync_fetch_and_or ((atomic), (val));                           \
}))
#define g_atomic_pointer_add(atomic, val) \
(G_GNUC_EXTENSION ({                                                          \
    G_STATIC_ASSERT (sizeof *(atomic) == sizeof (gpointer));            \
    (void) (0 ? (gpointer) *(atomic) : 0);                              \
    (void) (0 ? (val) ^ (val) : 0);                                     \
    (gssize) __sync_fetch_and_add ((atomic), (val));                    \
}))
#endif 
```

**Comment by etamme** [comment]
this makes life ... a lot easier, thank you

**Comment by etamme** [comment]
[PR 148](https://github.com/sipwise/rtpengine/pull/148) fixes this issue
